import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'


export default function Home({results }) {
  
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </Head>

      

      
      <Header />

      
      <Nav />

      <Results results = {results}/> 

    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  
  const request = await fetch(
    `https://api.themoviedb.org/3${
   requests[genre]?.url || requests.fetchTrending.url
  }`
  ).then(res => res.json());
  
 return {
   props: {
     results: request.results,
   },
 };
}